### ISSUE TITLE
Error on command.

### ISSUE THREAD

**Issue by Ianardo-DiCaprio** [PumPum7/PumCogs#10]
**Describe the bug**
```Traceback (most recent call last):
  File "/home/Ian/my_env/lib/python3.7/site-packages/discord/ext/commands/core.py", line 61, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/Ian/DiscordBot/cogs/CogManager/cogs/nicknamechanger/nicknamechanger.py", line 74, in nickname_checker
    link = await self.mystbin(stringx="No users with special characters in their nicknames could be found.")
  File "/home/Ian/DiscordBot/cogs/CogManager/cogs/nicknamechanger/nicknamechanger.py", line 210, in mystbin
    post = await post.json()
  File "/home/Ian/my_env/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 938, in json
    headers=self.headers)
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/Ian/my_env/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 898, in invoke
    await ctx.command.invoke(ctx)
  File "/home/Ian/my_env/lib/python3.7/site-packages/discord/ext/commands/core.py", line 614, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/Ian/my_env/lib/python3.7/site-packages/discord/ext/commands/core.py", line 70, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html'```

**To Reproduce**
Steps to reproduce the behavior:
1. Use the [p]check command
2. Click on the reaction
3. See error

**Expected behaviour**
The command to check nicknames and receive an embed with a link to mystbin with the changed names.

**Discord Version**
 - Canary
 - Latest

**Python Version**
 - Python 3.7.1

**Additional context**
I had changed it to listen for y or yes instead of just the reaction which was working fine, but I still get this error even when reverting back to the original version of the cog.

**Comment by PumPum7** [comment]
It should be fixed now. Looks like there was an error with mystb.in which returned unwanted information.
