### ISSUE TITLE
[NicknameChanger] Send to target not as expected

### ISSUE THREAD

**Issue by aikaterna** [PumPum7/PumCogs#14]
**Describe the bug**
When a user used `[p]check @targetuser` it errored out.

**To Reproduce**
1. Use [p]check in a server with the manage_nicknames permission, with a user target for the "output" parameter.
2. https://github.com/PumPum7/PumCogs/blob/4116e010b4e22120e96453a9a6ad939e3a663377/nicknamechanger/nicknamechanger.py#L94 will error out as the method should be Member.send (`await ctx.author.send(embed=embed))`)

Error:
```
Traceback (most recent call last):
  File "/.../cat38/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/.../catcogs/nicknamechanger/nicknamechanger.py", line 94, in nickname_checker
    await ctx.message.author(embed=embed)
TypeError: 'Member' object is not callable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/.../cat38/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "/.../cat38/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/.../cat38/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: 'Member' object is not callable
```

**Expected behavior**
I expected the output to be sent to the user mentioned.

**Screenshots**
This was on a server I don't have access to.

**Discord Version**
N/A as it's not a display issue, but on stable on a Mac.

**Python Version**
3.8.6

**Additional context**
I am curious if the `output="channel"` arg on the check command is supposed to have the ability to go to a targeted text channel or a targeted user, or both, or I would have PRed a fix instead.

**Comment by PumPum7** [comment]
Fixed thanks for the report!
