### ISSUE TITLE
Give Away Cog

### ISSUE THREAD

**Issue by cyberofficial** [PumPum7/PumCogs#7]
**Describe the bug**

Something didn't go quite right: Command raised an exception: LookupError: No trigger by the name "date" was found. Please report this.

**To Reproduce**
Fresh install of RedBotv3
loaded downloader
Installed repo, installed giveaway cog
did my command: m/giveaway start 10m hello
[m/ being my prefix]

get this message:
Something didn't go quite right: Command raised an exception: LookupError: No trigger by the name "date" was found. Please report this.

**Screenshots**
![image](https://user-images.githubusercontent.com/19499442/48035098-40676d80-e130-11e8-962a-7b8dfa2e7f60.png)

```python
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Users\kille\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\ext\commands\core.py", line 61, in wrapped
    ret = await coro(*args, **kwargs)
  File "F:\SkyNet3\cogs\CogManager\cogs\giveaway\giveaway.py", line 83, in cmd_giveaway
    await self.start_giveaway(end_time, prize, channel, winners)
  File "F:\SkyNet3\cogs\CogManager\cogs\giveaway\giveaway.py", line 279, in start_giveaway
    args=(prize, channel, msg.id, winners, end_time, giveaway_id),
  File "F:\SkyNet3\cogs\Downloader\lib\apscheduler\schedulers\base.py", line 416, in add_job
    'trigger': self._create_trigger(trigger, trigger_args),
  File "F:\SkyNet3\cogs\Downloader\lib\apscheduler\schedulers\base.py", line 918, in _create_trigger
    return self._create_plugin_instance('trigger', trigger, trigger_args)
  File "F:\SkyNet3\cogs\Downloader\lib\apscheduler\schedulers\base.py", line 901, in _create_plugin_instance
    raise LookupError('No {0} by the name "{1}" was found'.format(type_, alias))
LookupError: No trigger by the name "date" was found
```

**Discord Version**
 - Stable
 - Are you on the latest update? Yes I am

**Python Version**
 - Are you using 3.6 or a newer/older version? 3.7

**Comment by cyberofficial** [comment]
```python
    async def start_giveaway(self, end_time, prize, channel, winners, donator_note=None, donator=None, giveaway_id=None):
        # starts a giveaway
        # creates the embed and sends it
        giveaway_embed = discord.Embed(
            color=discord.Color.blue(),
            title=f"{GIVEAWAY_EMOTE} GIVEAWAY! {GIVEAWAY_EMOTE}",
            description=f"**Prize:** {prize}\n"
                        f"**Possible winners:** {winners} {'member' if winners == 1 else 'members'}\n"
                        f"Click on the {GIVEAWAY_EMOTE} reaction to enter!"
        )
        giveaway_embed.timestamp = end_time
        giveaway_embed.set_footer(text="Ends at")
        if donator_note is not None:
            donator = discord.utils.get(channel.guild.members, id=donator)
            if donator is not None: donator = donator.name
            giveaway_embed.add_field(
                name=f"A message by {donator}:",
                value=donator_note
            )
        msg = await channel.send(embed=giveaway_embed)
        await msg.add_reaction(f"{GIVEAWAY_EMOTE}")
        # sets up the scheduler
        scheduler = self.scheduler
        scheduler.add_job(
            func=self.giveaway_embed,
            trigger="date",
            run_date=end_time,
            args=(prize, channel, msg.id, winners, end_time, giveaway_id),
        )
        if not scheduler.running:
            scheduler.start()
        return True
```

This is what my debugger points to.
Right here

```python
Line 277            trigger="date",
```

**Comment by cyberofficial** [comment]
yes, i did install `pip install apscheduler` from the other error someone reported

**Comment by cyberofficial** [comment]
Fixed the issue. Reverted from python 3.7 to 3.6.6
